# Generated by Django 5.2.6 on 2025-09-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('sub_cast', models.CharField(blank=True, max_length=50, verbose_name='Sub Cast')),
                ('address', models.TextField(verbose_name='Address')),
                ('area', models.CharField(max_length=100, verbose_name='Area')),
                ('zone', models.CharField(max_length=50, verbose_name='Zone')),
                ('whatsapp_no', models.CharField(max_length=15, verbose_name='WhatsApp No')),
                ('alternate_no', models.CharField(blank=True, max_length=15, verbose_name='Alternate No')),
                ('family_members', models.PositiveIntegerField(verbose_name='Number of Family Members')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('vip', models.BooleanField(default=False, verbose_name='VIP Candidate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
