# Generated by Django 5.2.6 on 2025-09-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0002_remove_contact_created_at_alter_contact_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='alternate_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
