# Generated by Django 5.2.6 on 2025-09-09 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0003_alter_contact_alternate_no_alter_contact_whatsapp_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='હિરાપુરા સ્વાગત સમ્મેલન', max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=255)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('num_people', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField()),
                ('is_vip', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hira.event')),
            ],
        ),
    ]
