# Generated by Django 5.2.6 on 2025-09-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0004_event_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='upi_token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
