# Generated by Django 5.2.6 on 2025-10-05 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0006_phoneotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='user',
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_otps', to='hira.contact'),
        ),
    ]
