# Generated by Django 5.2.6 on 2025-10-09 11:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0007_remove_phoneotp_user_phoneotp_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1-5 overall satisfaction', null=True)),
                ('organization_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1-5 event organization', null=True)),
                ('food_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1-5 food / refreshments', null=True)),
                ('venue_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1-5 venue / facilities', null=True)),
                ('attended', models.BooleanField(default=True, help_text='Did they actually attend?')),
                ('would_recommend', models.BooleanField(blank=True, help_text='Would they recommend this event?', null=True)),
                ('highlights', models.TextField(blank=True, help_text='What did you like most?')),
                ('improvements', models.TextField(blank=True, help_text='What should we improve?')),
                ('allow_contact_for_followup', models.BooleanField(default=False)),
                ('contact_note', models.TextField(blank=True, help_text='If allow_contact_for_followup is True, note preferred follow up method.')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_feedbacks', to='hira.contact')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_feedbacks', to='hira.event')),
            ],
            options={
                'verbose_name': 'Post-event feedback',
                'verbose_name_plural': 'Post-event feedbacks',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PreEventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_experience_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1-5 rating for expected experience', null=True)),
                ('ease_of_registration', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1-5 registration process ease', null=True)),
                ('clarity_of_communications', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1-5 clarity of pre-event information', null=True)),
                ('will_attend', models.BooleanField(default=True, help_text='Does the person intend to attend?')),
                ('travel_help_needed', models.BooleanField(default=False, help_text='Does the person need travel help?')),
                ('expected_number_of_people', models.PositiveSmallIntegerField(default=1)),
                ('expectations', models.TextField(blank=True, help_text='What do you expect from the event?')),
                ('concerns', models.TextField(blank=True, help_text='Any concerns or special requests?')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_feedbacks', to='hira.contact')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_feedbacks', to='hira.event')),
            ],
            options={
                'verbose_name': 'Pre-event feedback',
                'verbose_name_plural': 'Pre-event feedbacks',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
