# Generated by Django 5.2.6 on 2025-10-11 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0008_posteventfeedback_preeventfeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posteventfeedback',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Post-event Feedback', 'verbose_name_plural': 'Post-event Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='preeventfeedback',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Pre-event Feedback', 'verbose_name_plural': 'Pre-event Feedbacks'},
        ),
        migrations.RemoveField(
            model_name='posteventfeedback',
            name='allow_contact_for_followup',
        ),
        migrations.RemoveField(
            model_name='posteventfeedback',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='posteventfeedback',
            name='contact_note',
        ),
        migrations.RemoveField(
            model_name='posteventfeedback',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='posteventfeedback',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='preeventfeedback',
            name='expected_number_of_people',
        ),
        migrations.RemoveField(
            model_name='preeventfeedback',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='preeventfeedback',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='preeventfeedback',
            name='travel_help_needed',
        ),
        migrations.RemoveField(
            model_name='preeventfeedback',
            name='will_attend',
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hira.contact'),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='food_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1–5 rating for food / refreshments', null=True),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='highlights',
            field=models.TextField(blank=True, help_text='What did you like the most about the event?'),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='improvements',
            field=models.TextField(blank=True, help_text='Any suggestions for improvement?'),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='organization_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1–5 rating for event organization', null=True),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='overall_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1–5 rating for overall satisfaction', null=True),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='venue_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1–5 rating for venue and facilities', null=True),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='would_recommend',
            field=models.BooleanField(blank=True, help_text='Would you recommend this event to others?', null=True),
        ),
        migrations.AlterField(
            model_name='preeventfeedback',
            name='clarity_of_communications',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1–5 rating for how clear event info was', null=True),
        ),
        migrations.AlterField(
            model_name='preeventfeedback',
            name='concerns',
            field=models.TextField(blank=True, help_text='Any questions or special requests?'),
        ),
        migrations.AlterField(
            model_name='preeventfeedback',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hira.contact'),
        ),
        migrations.AlterField(
            model_name='preeventfeedback',
            name='ease_of_registration',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1–5 rating for how easy registration was', null=True),
        ),
        migrations.AlterField(
            model_name='preeventfeedback',
            name='expectations',
            field=models.TextField(blank=True, help_text='What are you expecting from the event?'),
        ),
        migrations.AlterField(
            model_name='preeventfeedback',
            name='expected_experience_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1–5 rating for expected experience', null=True),
        ),
    ]
