# Generated by Django 5.2.6 on 2025-11-28 12:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0009_alter_posteventfeedback_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteventfeedback',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hira.contact', verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_feedbacks', to='hira.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='food_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1–5 rating for food / refreshments', null=True, verbose_name='Food Rating'),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='highlights',
            field=models.TextField(blank=True, help_text='What did you like the most about the event?', verbose_name='Highlights'),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='improvements',
            field=models.TextField(blank=True, help_text='Any suggestions for improvement?', verbose_name='Improvements'),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='organization_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1–5 rating for event organization', null=True, verbose_name='Organization Rating'),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='overall_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1–5 rating for overall satisfaction', null=True, verbose_name='Overall Satisfaction'),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At'),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='venue_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1–5 rating for venue and facilities', null=True, verbose_name='Venue Rating'),
        ),
        migrations.AlterField(
            model_name='posteventfeedback',
            name='would_recommend',
            field=models.BooleanField(blank=True, help_text='Would you recommend this event to others?', null=True, verbose_name='Would Recommend'),
        ),
        migrations.AlterField(
            model_name='preeventfeedback',
            name='clarity_of_communications',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1–5 rating for how clear event info was', null=True, verbose_name='Clarity of Communication Rating'),
        ),
        migrations.AlterField(
            model_name='preeventfeedback',
            name='concerns',
            field=models.TextField(blank=True, help_text='Any questions or special requests?', verbose_name='Concerns / Questions'),
        ),
        migrations.AlterField(
            model_name='preeventfeedback',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hira.contact', verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='preeventfeedback',
            name='ease_of_registration',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1–5 rating for how easy registration was', null=True, verbose_name='Ease of Registration Rating'),
        ),
        migrations.AlterField(
            model_name='preeventfeedback',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_feedbacks', to='hira.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='preeventfeedback',
            name='expectations',
            field=models.TextField(blank=True, help_text='What are you expecting from the event?', verbose_name='Expectations'),
        ),
        migrations.AlterField(
            model_name='preeventfeedback',
            name='expected_experience_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1–5 rating for expected experience', null=True, verbose_name='Expected Experience Rating'),
        ),
        migrations.AlterField(
            model_name='preeventfeedback',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At'),
        ),
        migrations.CreateModel(
            name='UserEventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_people', models.PositiveIntegerField(default=0)),
                ('total_paid', models.PositiveIntegerField(default=0)),
                ('is_vip', models.BooleanField(default=False)),
                ('is_fully_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hira.contact')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hira.event')),
            ],
            options={
                'unique_together': {('contact', 'event')},
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_added', models.PositiveIntegerField()),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_token', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hira.usereventbooking')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
