# Generated by Django 5.2.6 on 2025-11-29 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0010_alter_posteventfeedback_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteventfeedback',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='posteventfeedback',
            name='event',
        ),
        migrations.RemoveField(
            model_name='preeventfeedback',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='preeventfeedback',
            name='event',
        ),
        migrations.AlterUniqueTogether(
            name='usereventbooking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usereventbooking',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='usereventbooking',
            name='event',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('people_count', models.PositiveIntegerField(default=1)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hira.contact')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hira.event')),
            ],
        ),
        migrations.DeleteModel(
            name='BookingHistory',
        ),
        migrations.DeleteModel(
            name='PostEventFeedback',
        ),
        migrations.DeleteModel(
            name='PreEventFeedback',
        ),
        migrations.DeleteModel(
            name='UserEventBooking',
        ),
    ]
