# Generated by Django 5.2.6 on 2025-11-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0011_remove_posteventfeedback_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Hirapura Event Portal', max_length=200)),
                ('address', models.TextField(default='Hirapura Village, Community Ground Road, Hirapura, Gujarat, India')),
                ('phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('email', models.EmailField(default='info@hirapuraevents.com', max_length=254)),
                ('office_hours', models.CharField(default='Monday – Saturday: 9:00 AM – 6:00 PM', max_length=100)),
                ('invitation_image', models.ImageField(blank=True, null=True, upload_to='site_images/')),
            ],
            options={
                'verbose_name': 'Site Information',
                'verbose_name_plural': 'Site Information',
            },
        ),
    ]
