# Generated by Django 5.2.6 on 2025-11-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0013_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='about_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='about_text_gu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='about_title_en',
            field=models.CharField(default='About Hirapura Event Portal', max_length=255),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='about_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
