# Generated by Django 5.2.6 on 2025-11-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0014_siteinfo_about_text_en_siteinfo_about_text_gu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('expectations', models.TextField(blank=True)),
                ('additional_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
