# Generated by Django 5.2.6 on 2025-11-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0016_postfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
